import io
import re
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR

# --- 디자인 상수 (GEM Blue Theme) ---
COLOR_PRIMARY = RGBColor(0, 104, 201)  # Streamlit Blue
COLOR_DARK = RGBColor(49, 51, 63)      # Dark Grey
COLOR_WHITE = RGBColor(255, 255, 255)
COLOR_GREY = RGBColor(128, 128, 128)

def clean_text(text):
    """Markdown 문법 제거 (**Bold** 등)"""
    text = text.replace('**', '')
    return text.strip()

def add_design_bar(slide):
    """슬라이드 왼쪽에 디자인 바 추가 (템플릿 느낌)"""
    # 왼쪽 0.3인치 너비의 파란색 띠
    left = top = 0
    width = Inches(0.25)
    height = Inches(7.5) # 기본 슬라이드 높이
    
    shape = slide.shapes.add_shape(
        1, # msoShapeRectangle
        left, top, width, height
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = COLOR_PRIMARY
    shape.line.fill.background() # 선 없음

def create_title_slide(prs, title_text, subtitle_text="Generated by GEM Intern AI"):
    """표지 슬라이드 생성"""
    slide = prs.slides.add_slide(prs.slide_layouts[0]) # Title Layout
    
    title = slide.shapes.title
    title.text = title_text
    title.text_frame.paragraphs[0].font.color.rgb = COLOR_PRIMARY
    title.text_frame.paragraphs[0].font.bold = True
    
    subtitle = slide.placeholders[1]
    subtitle.text = subtitle_text
    subtitle.text_frame.paragraphs[0].font.color.rgb = COLOR_GREY
    
    return slide

def create_section_slide(prs, text):
    """챕터 간지 (파란 배경) 생성"""
    # Blank Layout 사용 후 배경색 채우기
    slide = prs.slides.add_slide(prs.slide_layouts[6]) 
    
    # 배경색 설정 (XML 조작 없이 도형으로 덮기)
    left = top = 0
    width = prs.slide_width
    height = prs.slide_height
    
    bg = slide.shapes.add_shape(1, left, top, width, height)
    bg.fill.solid()
    bg.fill.fore_color.rgb = COLOR_PRIMARY
    bg.line.fill.background()
    
    # 텍스트 박스 추가
    textbox = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(8), Inches(2))
    tf = textbox.text_frame
    tf.text = text
    tf.paragraphs[0].alignment = PP_ALIGN.CENTER
    tf.paragraphs[0].font.color.rgb = COLOR_WHITE
    tf.paragraphs[0].font.size = Pt(44)
    tf.paragraphs[0].font.bold = True
    
    return slide

def create_content_slide(prs, title_text):
    """본문 슬라이드 생성 (디자인 바 포함)"""
    slide = prs.slides.add_slide(prs.slide_layouts[1]) # Title and Content
    
    # 디자인 요소 추가
    add_design_bar(slide)
    
    # 제목 설정
    title = slide.shapes.title
    title.text = title_text
    title.text_frame.paragraphs[0].font.size = Pt(32)
    title.text_frame.paragraphs[0].font.color.rgb = COLOR_DARK
    title.text_frame.paragraphs[0].font.bold = True
    
    # 본문 영역 위치 조정 (디자인 바와 겹치지 않게)
    body = slide.placeholders[1]
    body.left = Inches(1.0) # 왼쪽 여백 확보
    body.width = Inches(8.5)
    
    return slide, body.text_frame

def create_ppt(markdown_text):
    """Markdown -> Structured PPT 변환"""
    prs = Presentation()
    
    lines = markdown_text.split('\n')
    
    # 상태 변수
    current_slide = None
    text_frame = None
    is_first_header = True # 첫 번째 #은 표지로 사용
    
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        clean_line = clean_text(line)
        
        # 1. 메인 헤더 (#) -> 표지 또는 섹션 간지
        if line.strip().startswith('# '):
            content = line.strip().replace('# ', '').strip()
            
            if is_first_header:
                # 첫 번째 #은 문서 전체 제목(표지)으로 간주
                create_title_slide(prs, content)
                is_first_header = False
                current_slide = None # 표지 다음엔 내용 슬라이드 초기화
                text_frame = None
            else:
                # 두 번째부터는 챕터 간지(Section Divider)로 사용
                create_section_slide(prs, content)
                current_slide = None
                text_frame = None # 간지에는 본문 안 넣음
            i += 1
            continue

        # 2. 서브 헤더 (##) -> 새 본문 슬라이드
        elif line.strip().startswith('## '):
            content = line.strip().replace('## ', '').strip()
            current_slide, text_frame = create_content_slide(prs, content)
            i += 1
            continue
            
        # 3. 소제목 (###) -> 슬라이드 내 강조 텍스트 (Bold Paragraph)
        elif line.strip().startswith('### '):
            if text_frame: # 현재 작성 중인 슬라이드가 있을 때만
                p = text_frame.add_paragraph()
                p.text = line.strip().replace('### ', '').strip()
                p.font.bold = True
                p.font.size = Pt(20)
                p.font.color.rgb = COLOR_PRIMARY
                p.space_before = Pt(12) # 위쪽 여백
            i += 1
            continue

        # 4. 목록 (Bullet Points)
        elif re.match(r'^\s*([-*]|\d+\.)\s', line):
            # 슬라이드가 없는데 내용이 나오면, "Overview" 슬라이드 자동 생성
            if current_slide is None:
                current_slide, text_frame = create_content_slide(prs, "Overview")

            match = re.match(r'^(\s*)([-*]|\d+\.)\s+(.*)', line)
            if match:
                indent_str, marker, content = match.groups()
                clean_content = clean_text(content)
                
                # 레벨 계산
                spaces = indent_str.replace('\t', '  ')
                level = len(spaces) // 2
                if level > 4: level = 4
                
                # 문단 추가
                p = text_frame.add_paragraph()
                p.text = clean_content
                p.level = level
                p.font.size = Pt(18)
                
                # 줄간격 조정
                p.space_after = Pt(6)

        # 5. 그 외 일반 텍스트
        elif line.strip():
            # 슬라이드가 없으면 생성
            if current_slide is None:
                current_slide, text_frame = create_content_slide(prs, "Analysis Details")
            
            p = text_frame.add_paragraph()
            p.text = clean_line
            p.level = 0
            p.font.size = Pt(18)
            
        i += 1
            
    # 파일 저장
    bio = io.BytesIO()
    prs.save(bio)
    return bio.getvalue()