import io
import re
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

def clean_text(text):
    """Markdown 문법(**Bold**)을 제거하거나 처리합니다."""
    # PPT에서는 텍스트 런(Run) 단위로 스타일을 입혀야 해서 복잡하므로, 
    # v1에서는 ** 표시를 제거하고 텍스트만 깔끔하게 넣습니다.
    text = text.replace('**', '')
    return text.strip()

def create_ppt(markdown_text):
    """Markdown 텍스트를 PPT 파일로 변환합니다."""
    prs = Presentation()
    
    # 레이아웃 상수 (기본 테마 기준)
    # 0: Title Slide (제목 + 부제목)
    # 1: Title and Content (제목 + 내용)
    SLIDE_TITLE = 0
    SLIDE_CONTENT = 1
    
    lines = markdown_text.split('\n')
    
    # 1. 표지 슬라이드 생성 (첫 번째 슬라이드)
    # 파일명이나 첫 번째 헤더를 제목으로 쓸 수 있지만, 일단 기본 표지 생성
    slide_layout = prs.slide_layouts[SLIDE_TITLE]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = "Investment Review Report"
    subtitle.text = "Generated by GEM Intern AI"
    
    # 현재 작업 중인 슬라이드와 텍스트 프레임
    current_slide = None
    body_shape = None
    tf = None
    
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        
        # 1. 헤더 처리 (#, ##, ###) -> 새 슬라이드 생성
        if line.strip().startswith('#'):
            # 레벨 확인 (# 개수)
            level = len(line.strip().split(' ')[0])
            content_text = line.strip().lstrip('#').strip()
            
            # 새 슬라이드 추가 (제목 + 내용 레이아웃)
            slide_layout = prs.slide_layouts[SLIDE_CONTENT]
            current_slide = prs.slides.add_slide(slide_layout)
            
            # 제목 설정
            title_shape = current_slide.shapes.title
            title_shape.text = content_text
            
            # 본문 텍스트 프레임 확보
            body_shape = current_slide.placeholders[1]
            tf = body_shape.text_frame
            tf.clear() # 기본 텍스트 제거 (필요시)
            
            i += 1
            continue
            
        # 2. 목록 처리 (-, *) -> 글머리 기호
        elif re.match(r'^\s*([-*]|\d+\.)\s', line):
            if current_slide is None:
                # 헤더 없이 내용이 먼저 나오면 슬라이드 하나 생성
                slide_layout = prs.slide_layouts[SLIDE_CONTENT]
                current_slide = prs.slides.add_slide(slide_layout)
                body_shape = current_slide.placeholders[1]
                tf = body_shape.text_frame
                current_slide.shapes.title.text = "Overview"

            # 들여쓰기 레벨 계산
            match = re.match(r'^(\s*)([-*]|\d+\.)\s+(.*)', line)
            if match:
                indent_str, marker, content = match.groups()
                
                # 탭이나 공백 2개를 1레벨로 간주
                spaces = indent_str.replace('\t', '  ')
                level = len(spaces) // 2
                if level > 4: level = 4 # PPT 들여쓰기 제한

                # 단락 추가
                p = tf.add_paragraph()
                p.text = clean_text(content)
                p.level = level # 들여쓰기 적용
                
                # 폰트 사이즈 조정 (레벨별로 조금씩 줄이기 옵션)
                if level == 0:
                    p.font.size = Pt(20)
                else:
                    p.font.size = Pt(18)
            i += 1
            continue

        # 3. 표 처리 (|...|) -> 텍스트로 단순화해서 넣기 (PPT 표 생성은 복잡하므로)
        elif line.strip().startswith('|'):
            # 표는 별도 슬라이드나 텍스트 박스로 처리하기 어려우므로
            # v1에서는 텍스트 형태로 줄맞춤하여 넣습니다.
            if current_slide and tf:
                p = tf.add_paragraph()
                p.text = clean_text(line)
                p.font.name = 'Courier New' # 고정폭 글꼴 사용
                p.font.size = Pt(12)
            i += 1
            continue

        # 4. 일반 텍스트
        else:
            if line.strip():
                if current_slide is None:
                    slide_layout = prs.slide_layouts[SLIDE_CONTENT]
                    current_slide = prs.slides.add_slide(slide_layout)
                    body_shape = current_slide.placeholders[1]
                    tf = body_shape.text_frame
                
                p = tf.add_paragraph()
                p.text = clean_text(line)
                p.level = 0
            i += 1
            
    # 바이너리 스트림으로 저장
    bio = io.BytesIO()
    prs.save(bio)
    return bio.getvalue()