import io
import re
import datetime
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE

# --- 디자인 상수 (GEM Blue Theme) ---
COLOR_PRIMARY = RGBColor(0, 104, 201)  # Streamlit Blue
COLOR_HEADER_BG = RGBColor(30, 58, 138)  # Dark Blue (HTML: #1E3A8A)
COLOR_WHITE = RGBColor(255, 255, 255)
COLOR_GREY = RGBColor(128, 128, 128)
COLOR_LIGHT_BLUE = RGBColor(219, 234, 254)  # Light Blue for table header
COLOR_LIGHT_GREY = RGBColor(245, 245, 245)  # 요약 배경색

# 4:3 슬라이드 크기
SLIDE_WIDTH = Inches(10)
SLIDE_HEIGHT = Inches(7.5)


def clean_text(text):
    """Markdown 문법 제거 (**Bold** 등)"""
    text = text.replace('**', '')
    return text.strip()


def add_master_design(slide, title_text="Gemini Investment Report"):
    """슬라이드 상단에 마스터 디자인(헤더 바) 추가"""
    # 상단 헤더 바 (Dark Blue)
    shape = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        0, 0, SLIDE_WIDTH, Inches(0.5)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = COLOR_HEADER_BG
    shape.line.fill.background()

    # 헤더 텍스트 (좌측)
    textbox = slide.shapes.add_textbox(Inches(0.3), Inches(0.1), Inches(7), Inches(0.35))
    p = textbox.text_frame.paragraphs[0]
    p.text = title_text
    p.font.color.rgb = COLOR_WHITE
    p.font.size = Pt(11)
    p.font.bold = True

    # 날짜 (우측)
    date_str = datetime.date.today().strftime("%Y-%m-%d")
    date_box = slide.shapes.add_textbox(Inches(7.5), Inches(0.1), Inches(2.2), Inches(0.35))
    p_date = date_box.text_frame.paragraphs[0]
    p_date.text = date_str
    p_date.font.color.rgb = COLOR_WHITE
    p_date.font.size = Pt(10)
    p_date.alignment = PP_ALIGN.RIGHT


def create_title_slide(prs, title_text, subtitle_text="Generated by GEM Intern AI"):
    """표지 슬라이드 생성"""
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # 배경 전체를 Dark Blue로
    bg = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SLIDE_WIDTH, SLIDE_HEIGHT)
    bg.fill.solid()
    bg.fill.fore_color.rgb = COLOR_HEADER_BG
    bg.line.fill.background()

    # 제목 텍스트박스
    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(2.8), Inches(9), Inches(1.2))
    tf = title_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title_text
    p.alignment = PP_ALIGN.CENTER
    p.font.color.rgb = COLOR_WHITE
    p.font.size = Pt(40)
    p.font.bold = True

    # 부제목
    sub_box = slide.shapes.add_textbox(Inches(0.5), Inches(4.2), Inches(9), Inches(0.6))
    p_sub = sub_box.text_frame.paragraphs[0]
    p_sub.text = subtitle_text
    p_sub.alignment = PP_ALIGN.CENTER
    p_sub.font.color.rgb = COLOR_LIGHT_BLUE
    p_sub.font.size = Pt(18)

    # 날짜
    date_str = datetime.date.today().strftime("%Y년 %m월 %d일")
    date_box = slide.shapes.add_textbox(Inches(0.5), Inches(6.5), Inches(9), Inches(0.4))
    p_date = date_box.text_frame.paragraphs[0]
    p_date.text = date_str
    p_date.alignment = PP_ALIGN.CENTER
    p_date.font.color.rgb = COLOR_WHITE
    p_date.font.size = Pt(14)

    return slide


def create_section_slide(prs, text):
    """챕터 간지 (파란 배경) 생성"""
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # 배경색 설정
    bg = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SLIDE_WIDTH, SLIDE_HEIGHT)
    bg.fill.solid()
    bg.fill.fore_color.rgb = COLOR_HEADER_BG
    bg.line.fill.background()

    # 텍스트 박스 추가
    textbox = slide.shapes.add_textbox(Inches(0.5), Inches(3), Inches(9), Inches(1.5))
    tf = textbox.text_frame
    tf.word_wrap = True
    tf.paragraphs[0].text = text
    tf.paragraphs[0].alignment = PP_ALIGN.CENTER
    tf.paragraphs[0].font.color.rgb = COLOR_WHITE
    tf.paragraphs[0].font.size = Pt(36)
    tf.paragraphs[0].font.bold = True

    return slide


def create_two_column_slide(prs, summary_text, left_title, left_items, right_title, right_items):
    """
    새로운 2단 레이아웃 슬라이드
    ┌─────────────────────────────┐
    │  헤더                        │
    ├─────────────────────────────┤
    │  요약 (2줄)                  │
    ├──────────────┬──────────────┤
    │ 좌측 제목     │ 우측 제목     │
    │ (내용)       │ (내용)        │
    └──────────────┴──────────────┘
    """
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # 헤더 바
    add_master_design(slide)

    # 요약 영역 배경 (연한 회색)
    summary_bg = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(0.3), Inches(0.6), Inches(9.4), Inches(0.9)
    )
    summary_bg.fill.solid()
    summary_bg.fill.fore_color.rgb = COLOR_LIGHT_GREY
    summary_bg.line.fill.background()

    # 요약 텍스트
    summary_box = slide.shapes.add_textbox(Inches(0.4), Inches(0.65), Inches(9.2), Inches(0.8))
    summary_tf = summary_box.text_frame
    summary_tf.word_wrap = True
    p_sum = summary_tf.paragraphs[0]
    p_sum.text = summary_text if summary_text else ""
    p_sum.font.size = Pt(11)
    p_sum.font.color.rgb = RGBColor(50, 50, 50)

    # 구분선
    line = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(0.3), Inches(1.55), Inches(9.4), Inches(0.02)
    )
    line.fill.solid()
    line.fill.fore_color.rgb = COLOR_HEADER_BG
    line.line.fill.background()

    # === 좌측 컬럼 ===
    # 좌측 제목 배경
    left_title_bg = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(0.3), Inches(1.65), Inches(4.55), Inches(0.45)
    )
    left_title_bg.fill.solid()
    left_title_bg.fill.fore_color.rgb = COLOR_HEADER_BG
    left_title_bg.line.fill.background()

    # 좌측 제목 텍스트
    left_title_box = slide.shapes.add_textbox(Inches(0.4), Inches(1.7), Inches(4.35), Inches(0.4))
    p_lt = left_title_box.text_frame.paragraphs[0]
    p_lt.text = left_title if left_title else "Key Points"
    p_lt.font.size = Pt(14)
    p_lt.font.color.rgb = COLOR_WHITE
    p_lt.font.bold = True

    # 좌측 내용
    left_content_box = slide.shapes.add_textbox(Inches(0.4), Inches(2.2), Inches(4.45), Inches(5.0))
    left_tf = left_content_box.text_frame
    left_tf.word_wrap = True
    add_items_to_textframe(left_tf, left_items)

    # === 우측 컬럼 ===
    # 우측 제목 배경
    right_title_bg = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(5.15), Inches(1.65), Inches(4.55), Inches(0.45)
    )
    right_title_bg.fill.solid()
    right_title_bg.fill.fore_color.rgb = COLOR_HEADER_BG
    right_title_bg.line.fill.background()

    # 우측 제목 텍스트
    right_title_box = slide.shapes.add_textbox(Inches(5.25), Inches(1.7), Inches(4.35), Inches(0.4))
    p_rt = right_title_box.text_frame.paragraphs[0]
    p_rt.text = right_title if right_title else "Details"
    p_rt.font.size = Pt(14)
    p_rt.font.color.rgb = COLOR_WHITE
    p_rt.font.bold = True

    # 우측 내용
    right_content_box = slide.shapes.add_textbox(Inches(5.25), Inches(2.2), Inches(4.45), Inches(5.0))
    right_tf = right_content_box.text_frame
    right_tf.word_wrap = True
    add_items_to_textframe(right_tf, right_items)

    return slide


def add_items_to_textframe(tf, items):
    """텍스트프레임에 아이템 추가"""
    if not items:
        return

    for idx, item in enumerate(items):
        if idx == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()

        if item.get('type') == 'bullet':
            p.text = "• " + item['text']
            p.font.size = Pt(12)
            p.space_after = Pt(4)
            # 들여쓰기 레벨에 따라 왼쪽 마진
            level = item.get('level', 0)
            if level > 0:
                p.text = "  " * level + "- " + item['text']
        elif item.get('type') == 'subheader':
            p.text = item['text']
            p.font.bold = True
            p.font.size = Pt(13)
            p.font.color.rgb = COLOR_HEADER_BG
            p.space_before = Pt(6)
        else:
            p.text = item['text']
            p.font.size = Pt(12)
            p.space_after = Pt(3)


def create_table_slide(prs, title_text, table_data):
    """표 슬라이드 생성"""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    add_master_design(slide)

    # 제목
    title_box = slide.shapes.add_textbox(Inches(0.3), Inches(0.6), Inches(9.4), Inches(0.5))
    p_title = title_box.text_frame.paragraphs[0]
    p_title.text = title_text
    p_title.font.size = Pt(20)
    p_title.font.color.rgb = COLOR_HEADER_BG
    p_title.font.bold = True

    if not table_data or len(table_data) < 2:
        return slide

    rows = len(table_data)
    cols = len(table_data[0])

    # 표 크기
    table_width = Inches(9.4)
    table_height = Inches(min(5.5, 0.4 * rows))

    # 표 추가
    table = slide.shapes.add_table(rows, cols, Inches(0.3), Inches(1.2), table_width, table_height).table

    # 열 너비 균등 분배
    col_width = int(table_width / cols)
    for col_idx in range(cols):
        table.columns[col_idx].width = col_width

    # 데이터 채우기
    for row_idx, row_data in enumerate(table_data):
        for col_idx, cell_text in enumerate(row_data):
            if col_idx >= len(row_data):
                continue
            cell = table.cell(row_idx, col_idx)
            cell.text = clean_text(cell_text)

            para = cell.text_frame.paragraphs[0]
            para.font.size = Pt(10)
            para.alignment = PP_ALIGN.CENTER

            if row_idx == 0:
                cell.fill.solid()
                cell.fill.fore_color.rgb = COLOR_HEADER_BG
                para.font.color.rgb = COLOR_WHITE
                para.font.bold = True
            else:
                if row_idx % 2 == 0:
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = COLOR_LIGHT_BLUE
                para.font.color.rgb = RGBColor(30, 30, 30)

    return slide


def parse_markdown_table(lines, start_idx):
    """Markdown 테이블 파싱"""
    table_data = []
    i = start_idx

    while i < len(lines):
        line = lines[i].strip()
        if line.startswith('|') and line.endswith('|'):
            if re.match(r'^\|[\s\-:]+\|', line):
                i += 1
                continue
            cells = [c.strip() for c in line.split('|')[1:-1]]
            if cells:
                table_data.append(cells)
            i += 1
        else:
            break

    return table_data, i


def generate_summary(left_items, right_items):
    """좌/우 컬럼 내용에서 2줄 요약 생성"""
    summary_parts = []

    # 좌측 첫 번째 불릿
    for item in left_items:
        if item.get('type') == 'bullet':
            summary_parts.append(item['text'][:50])
            break

    # 우측 첫 번째 불릿
    for item in right_items:
        if item.get('type') == 'bullet':
            summary_parts.append(item['text'][:50])
            break

    if summary_parts:
        return " | ".join(summary_parts)
    return ""


def create_ppt(markdown_text):
    """Markdown -> Structured PPT 변환 (4:3, 새 2단 레이아웃)"""
    prs = Presentation()
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT

    lines = markdown_text.split('\n')

    # 상태 변수
    is_first_header = True
    current_section = ""  # ## 섹션 제목
    left_title = ""
    right_title = ""
    left_items = []
    right_items = []
    current_column = 'left'
    pending_slides = []  # (summary, left_title, left_items, right_title, right_items)

    def flush_slide():
        """현재 슬라이드 데이터를 저장"""
        nonlocal left_title, right_title, left_items, right_items, current_column
        if left_items or right_items:
            summary = generate_summary(left_items, right_items)
            pending_slides.append((summary, left_title, left_items.copy(), right_title, right_items.copy()))
        left_title = ""
        right_title = ""
        left_items = []
        right_items = []
        current_column = 'left'

    i = 0
    while i < len(lines):
        line = lines[i].rstrip()

        # 1. 메인 헤더 (#) -> 표지 또는 섹션 간지
        if line.strip().startswith('# ') and not line.strip().startswith('## '):
            flush_slide()
            content = line.strip()[2:].strip()

            if is_first_header:
                create_title_slide(prs, content)
                is_first_header = False
            else:
                # 이전 pending 슬라이드들 생성
                for slide_data in pending_slides:
                    create_two_column_slide(prs, *slide_data)
                pending_slides.clear()
                create_section_slide(prs, content)

            i += 1
            continue

        # 2. 서브 헤더 (##) -> 새 슬라이드 시작 신호
        elif line.strip().startswith('## '):
            flush_slide()
            current_section = line.strip()[3:].strip()

            # 다음에 테이블이 있는지 확인
            j = i + 1
            while j < len(lines) and not lines[j].strip():
                j += 1

            if j < len(lines) and lines[j].strip().startswith('|'):
                # pending 슬라이드들 먼저 생성
                for slide_data in pending_slides:
                    create_two_column_slide(prs, *slide_data)
                pending_slides.clear()

                table_data, end_idx = parse_markdown_table(lines, j)
                if table_data:
                    create_table_slide(prs, current_section, table_data)
                    i = end_idx
                    continue

            i += 1
            continue

        # 3. 소제목 (###) -> 컬럼 제목으로 사용
        elif line.strip().startswith('### '):
            content = line.strip()[4:].strip()

            # 좌측 제목이 비어있으면 좌측, 아니면 우측
            if not left_title:
                left_title = content
                current_column = 'left'
            elif not right_title:
                right_title = content
                current_column = 'right'
            else:
                # 이미 양쪽 제목이 있으면 새 슬라이드 시작
                flush_slide()
                left_title = content
                current_column = 'left'

            i += 1
            continue

        # 4. 테이블 감지
        elif line.strip().startswith('|'):
            # pending 슬라이드들 먼저 생성
            for slide_data in pending_slides:
                create_two_column_slide(prs, *slide_data)
            pending_slides.clear()
            flush_slide()

            table_data, end_idx = parse_markdown_table(lines, i)
            if table_data:
                create_table_slide(prs, current_section or "Data", table_data)

            i = end_idx
            continue

        # 5. 목록 (Bullet Points)
        elif re.match(r'^\s*([-*]|\d+\.)\s', line):
            match = re.match(r'^(\s*)([-*]|\d+\.)\s+(.*)', line)
            if match:
                indent_str, _, content = match.groups()
                clean_content = clean_text(content)

                spaces = indent_str.replace('\t', '  ')
                level = min(len(spaces) // 2, 3)

                item = {'type': 'bullet', 'text': clean_content, 'level': level}

                if current_column == 'left':
                    left_items.append(item)
                else:
                    right_items.append(item)

            i += 1
            continue

        # 6. 구분선 (---) -> 무시 또는 컬럼 전환
        elif line.strip() == '---':
            if current_column == 'left' and left_items:
                current_column = 'right'
            i += 1
            continue

        # 7. 그 외 일반 텍스트
        elif line.strip():
            item = {'type': 'text', 'text': clean_text(line)}
            if current_column == 'left':
                left_items.append(item)
            else:
                right_items.append(item)

        i += 1

    # 마지막 슬라이드 처리
    flush_slide()
    for slide_data in pending_slides:
        create_two_column_slide(prs, *slide_data)

    # 파일 저장
    bio = io.BytesIO()
    prs.save(bio)
    return bio.getvalue()
